name: sync

# Controls when the workflow will run
on:

  # Trigger the workflow on all pushes to the named branches and all tags
  push:
    branches:
    - 'master'
    tags:
    - '**'

jobs:

  # Calls a reusable CI workflow to sync the current with a remote repository.
  #   It will correctly handle addition of any new and removal of existing Git objects.
  sync:
    name: sync
    uses: ecmwf-actions/reusable-workflows/.github/workflows/sync.yml@v2
    secrets:
      target_repository: ESCAPE/dwarf-p-radiation-ecrad
      target_username: ClonedDuck
      target_token: ${{ secrets.BITBUCKET_PAT }}
